### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by CostacheDanielConstantin** [iamkdev/phpmongo-crud#1]
As previously mentioned this repo has helped me a lot ! Cant thank you enough.

However a specific search feature would be amazing.

This is just for educational purposes : I have been trying to do it with no help for a few days but no luck so far. I have also opened a stackoverflow question.
http://stackoverflow.com/questions/29567179/specific-search-in-mongodb-records-within-a-web-page-php

**Comment by a45b** [comment]
I updated the repo with search feature. Hope it help you.
