### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by CostacheDanielConstantin** [iamkdev/phpmongo-crud#2]
I also wrote you on your Gm.  instant messaging. 

The search feature works amazing! You are really good.

I mentioned this to you in a previous message....is it possible to have a feature that would stop duplicates from going in the database? For example you insert a title " Tom&Jerry " and author "Hanna Barbera"  and after that you try to insert again " Tom&Jerry" a message like "Sorry, that cartoon is already in the DB" - would it be possible to have that? (this is the second and last feature I ask for)

**Comment by a45b** [comment]
Add the checking for Duplicate entry when save or update. But better when you add index. Read some books on mongodb and php will help you doing this stuff.

Please, don't copy and paste your msg everywhere. By the way, I am happy my work helped you in learning.
